WebBookStore/Controllers/BookStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using WebBookStore.Models;

namespace WebBookStore.Controllers
{
    public class BookStoreController : ApiController
    {
        private ModelOperation modelOperation;

        public BookStoreController()
        {
            modelOperation = new ModelOperation();
        }

        public BookStoreController(ModelOperation modelOperation)
        {
            this.modelOperation = modelOperation;
        }

        public IHttpActionResult Get()
        {
            List<BookStoreModel> book = modelOperation.GetDetails();

            if (book.Count > 0)
            {
                return Ok(book);
            }
            else
            {
                return NotFound();
            }
        }

        public IHttpActionResult Getbookcon(int id)
        {
            BookStoreModel model = null;

            model = modelOperation.GetBookById(id);

            if (model != null)
            {
                return Ok(model);
            }
            else
            {
                return NotFound();
            }
        }

        public IHttpActionResult Post([FromBody]BookStoreModel bookModel)
        {
            if (!ModelState.IsValid)
                return BadRequest("Invalid data.");

            int res = modelOperation.AddBooks(bookModel);

            if (res != 0)
            {
                return Ok("Success inserted book");
            }
            else
            {
                return BadRequest("Not Inserted");
            }
        }

        public IHttpActionResult PutIntoFavList(int id, [FromBody]BookStoreModel bookModel)
        {
            if (!ModelState.IsValid)
                return BadRequest("Not a valid model");

            int res = modelOperation.PutIntoFavList(id, bookModel);

            if (res != 0)
            {
                return Ok();
            }
            else
            {
                return NotFound();
            }
        }

        [Route("api/BookStore/GetFavList")]
        public IHttpActionResult GetFavList()
        {
            List<BookStoreModel> book = modelOperation.GetFavList();

            if (book.Count > 0)
            {
                return Ok(book);
            }
            else
            {
                return NotFound();
            }
        }

        public IHttpActionResult Delete(int id)
        {
            int res = modelOperation.Delete(id);

            if (res != 0)
            {
                return Ok("Deleted Success");
            }
            else
            {
                return BadRequest("Not Deleted");
            }
        }
    }
}

WebBookStore/Controllers/BookStoreMVCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebBookStore.Models;

namespace WebBookStore.Controllers
{
    public class BookStoreMVCController : Controller
    {
        ModelOperation modelOperation = new ModelOperation();
        
        public ActionResult Index()
        {
            Session.Clear();
            Session.RemoveAll();
            Session.Abandon();
            FormsAuthentication.SignOut();
            return View();
        }

        public ActionResult BookStore()
        {
            return View();
        }

        public ActionResult User()
        {
            return View();
        }

        public ActionResult Details()
        {
            IEnumerable<BookStoreModel> books = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:61245/api/");
               
                var responseTask = client.GetAsync("BookStore");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<BookStoreModel>>();
                    readTask.Wait();

                    books = readTask.Result;
                }
                else 
                {
                    books = Enumerable.Empty<BookStoreModel>();

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            if (TempData["message"] != null)
            {
                TempData.Keep();
                return View(books);
            }
            else
            {
                TempData["message"] = "Invalid credetials";
                return RedirectToAction("LogHere", "Login");
            }
           
        }

       
        public ActionResult AddBooks()
        {
            return View(new BookStoreModel());
        }

        
        [HttpPost]
        public ActionResult AddBooks(BookStoreModel storeModel)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:61245/api/");

                //HTTP POST
                var postTask = client.PostAsJsonAsync<BookStoreModel>("BookStore", storeModel);
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Details");
                }
            }

            ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");

            return View(storeModel);
        }



        public ActionResult BookDetails()
        {
            IEnumerable<BookStoreModel> books = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:61245/api/");

                var responseTask = client.GetAsync("BookStore");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<BookStoreModel>>();
                    readTask.Wait();

                    books = readTask.Result;
                }
                else
                {
                    books = Enumerable.Empty<BookStoreModel>();

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            if (TempData["message"] != null)
            {
                TempData.Keep();
                return View(books);
            }
            else
            {
                TempData["message"] = "Invalid credetials";
                return RedirectToAction("LogHere", "Login");
            }

        }

        [HttpPost]
        public ActionResult AddFavBook( int id)
        {
            BookStoreModel books = null;
            
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:61245/api/");
              
                var responseTask = client.GetAsync("BookStore?id=" + id);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<BookStoreModel>();
                    readTask.Wait();

                    books = readTask.Result;
                }
            }

            return RedirectToAction("FavList");
        }
    

        public ActionResult FavList()
        {
            IEnumerable<BookStoreModel> books = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:61245/api/");

                var responseTask = client.GetAsync("BookStore/GetFavList");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<BookStoreModel>>();
                    readTask.Wait();

                    books = readTask.Result;
                }
                else
                {
                    books = Enumerable.Empty<BookStoreModel>();

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            if (TempData["message"] != null)
            {
                TempData.Keep();
                return View(books);
            }
            else
            {
                TempData["message"] = "Invalid credetials";
                return RedirectToAction("LogHere", "Login");
            }

        }



       
        public ActionResult Purchase(int id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:61245/api/");
               
                var deleteTask = client.DeleteAsync("BookStore/" + id);
                deleteTask.Wait();

                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {

                    return RedirectToAction("FavList");
                }
            }
            return RedirectToAction("FavList");
        }
   
    }
}

WebBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top alert-success">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "BookStore", "BookStoreMVC", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Details", "Details", "BookStoreMVC", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("AddBooks", "AddBooks", "BookStoreMVC", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
       
        <footer style="bottom:5px;">
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebBookStore/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top alert-success">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hi User Welcome", "User", "BookStoreMVC", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("BookDetails", "BookDetails", "BookStoreMVC", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("FavList", "FavList", "BookStoreMVC", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <footer style="bottom:5px;">
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>